export const metadata = { title: "Trijotech Admin" };

const adminTailwind = `min-h-screen bg-[#f3f6f8] font-[Poppins,sans-serif] text-[#344054]
  [&_.admin-login-page]:grid [&_.admin-login-page]:min-h-screen [&_.admin-login-page]:place-items-center [&_.admin-login-page]:bg-[linear-gradient(145deg,#17233d,#223253_65%,#087b71)] [&_.admin-login-page]:p-5
  [&_.admin-login-card]:w-full [&_.admin-login-card]:max-w-[440px] [&_.admin-login-card]:rounded-[18px] [&_.admin-login-card]:bg-white [&_.admin-login-card]:p-8 [&_.admin-login-card]:shadow-[0_24px_70px_rgba(23,35,61,.28)]
  [&_.admin-login-card_h1]:my-2 [&_.admin-login-card_h1]:text-3xl [&_.admin-login-card_h1]:font-bold [&_.admin-login-card_h1]:text-[#232555]
  [&_.admin-brand-mark]:grid [&_.admin-brand-mark]:h-12 [&_.admin-brand-mark]:w-12 [&_.admin-brand-mark]:place-items-center [&_.admin-brand-mark]:rounded-xl [&_.admin-brand-mark]:bg-[#087b71] [&_.admin-brand-mark]:font-extrabold [&_.admin-brand-mark]:text-white
  [&_.admin-eyebrow]:mt-5 [&_.admin-eyebrow]:text-xs [&_.admin-eyebrow]:font-bold [&_.admin-eyebrow]:uppercase [&_.admin-eyebrow]:tracking-[.15em] [&_.admin-eyebrow]:text-[#ee9e1e]
  [&_.admin-muted]:text-sm [&_.admin-muted]:leading-6 [&_.admin-muted]:text-[#667085]
  [&_.admin-login-card_label]:mt-5 [&_.admin-login-card_label]:block [&_.admin-login-card_label]:text-xs [&_.admin-login-card_label]:font-semibold
  [&_.admin-login-card_input]:mt-2 [&_.admin-login-card_input]:h-12 [&_.admin-login-card_input]:w-full [&_.admin-login-card_input]:rounded-[10px] [&_.admin-login-card_input]:border [&_.admin-login-card_input]:border-[#d2dae2] [&_.admin-login-card_input]:px-3 [&_.admin-login-card_input]:outline-none [&_.admin-login-card_input:focus]:border-[#087b71]
  [&_.admin-primary-button]:inline-flex [&_.admin-primary-button]:min-h-10 [&_.admin-primary-button]:cursor-pointer [&_.admin-primary-button]:items-center [&_.admin-primary-button]:justify-center [&_.admin-primary-button]:rounded-[9px] [&_.admin-primary-button]:border-0 [&_.admin-primary-button]:bg-[#087b71] [&_.admin-primary-button]:px-4 [&_.admin-primary-button]:py-[10px] [&_.admin-primary-button]:text-sm [&_.admin-primary-button]:font-bold [&_.admin-primary-button]:text-white [&_.admin-primary-button:disabled]:cursor-not-allowed [&_.admin-primary-button:disabled]:opacity-60
  [&_.admin-field-error]:mt-2 [&_.admin-field-error]:text-sm [&_.admin-field-error]:text-red-700
  [&_.admin-shell]:min-h-screen [&_.admin-shell]:bg-[#f3f6f8] [&_.admin-shell]:p-6 max-[720px]:[&_.admin-shell]:p-3
  [&_.admin-toolbar]:mx-auto [&_.admin-toolbar]:mb-5 [&_.admin-toolbar]:flex [&_.admin-toolbar]:max-w-[1440px] [&_.admin-toolbar]:flex-wrap [&_.admin-toolbar]:items-center [&_.admin-toolbar]:justify-between [&_.admin-toolbar]:gap-3 [&_.admin-toolbar]:rounded-xl [&_.admin-toolbar]:bg-[#17233d] [&_.admin-toolbar]:p-4 [&_.admin-toolbar]:text-white
  [&_.admin-card]:rounded-xl [&_.admin-card]:border [&_.admin-card]:border-[#e1e6eb] [&_.admin-card]:bg-white [&_.admin-card]:p-5 [&_.admin-card]:shadow-sm
  [&_.admin-field_label]:mb-2 [&_.admin-field_label]:block [&_.admin-field_label]:text-xs [&_.admin-field_label]:font-semibold
  [&_.admin-field_input]:w-full [&_.admin-field_input]:rounded-lg [&_.admin-field_input]:border [&_.admin-field_input]:border-[#d2dae2] [&_.admin-field_input]:bg-white [&_.admin-field_input]:p-[10px] [&_.admin-field_textarea]:w-full [&_.admin-field_textarea]:rounded-lg [&_.admin-field_textarea]:border [&_.admin-field_textarea]:border-[#d2dae2] [&_.admin-field_textarea]:p-[10px] [&_.admin-field_select]:w-full [&_.admin-field_select]:rounded-lg [&_.admin-field_select]:border [&_.admin-field_select]:border-[#d2dae2] [&_.admin-field_select]:p-[10px]
  [&_.admin-blog-layout]:mx-auto [&_.admin-blog-layout]:grid [&_.admin-blog-layout]:max-w-[1880px] [&_.admin-blog-layout]:grid-cols-[320px_minmax(0,1fr)] [&_.admin-blog-layout]:gap-5 max-[900px]:[&_.admin-blog-layout]:grid-cols-1
  [&_.admin-blog-list]:rounded-xl [&_.admin-blog-list]:border [&_.admin-blog-list]:border-[#e1e6eb] [&_.admin-blog-list]:bg-white [&_.admin-blog-list]:p-4
  [&_.admin-blog-editor]:rounded-xl [&_.admin-blog-editor]:border [&_.admin-blog-editor]:border-[#e1e6eb] [&_.admin-blog-editor]:bg-white [&_.admin-blog-editor]:p-5
  [&_.admin-form-section]:rounded-xl [&_.admin-form-section]:border [&_.admin-form-section]:border-[#e1e6eb] [&_.admin-form-section]:bg-white [&_.admin-form-section]:p-5
  [&_.admin-blog-actions]:mt-5 [&_.admin-blog-actions]:flex [&_.admin-blog-actions]:flex-wrap [&_.admin-blog-actions]:items-center [&_.admin-blog-actions]:justify-between [&_.admin-blog-actions]:gap-3 [&_.admin-blog-actions]:rounded-xl [&_.admin-blog-actions]:border [&_.admin-blog-actions]:border-[#d5dde4] [&_.admin-blog-actions]:bg-white [&_.admin-blog-actions]:p-4
  [&_.admin-topbar]:flex [&_.admin-topbar]:h-[72px] [&_.admin-topbar]:items-center [&_.admin-topbar]:justify-between [&_.admin-topbar]:gap-5 [&_.admin-topbar]:border-b [&_.admin-topbar]:border-[#dce2e8] [&_.admin-topbar]:bg-white [&_.admin-topbar]:px-6 max-[680px]:[&_.admin-topbar]:px-[14px]
  [&_.admin-topbar>div]:flex [&_.admin-topbar>div]:items-center [&_.admin-topbar>div]:gap-3 [&_.admin-topbar_strong]:block [&_.admin-topbar_strong]:text-base [&_.admin-topbar_strong]:text-[#17233d] [&_.admin-topbar_small]:block [&_.admin-topbar_small]:text-xs [&_.admin-topbar_small]:text-[#687386] max-[680px]:[&_.admin-topbar_small]:hidden
  [&_.admin-logo]:grid [&_.admin-logo]:h-[38px] [&_.admin-logo]:w-[38px] [&_.admin-logo]:place-items-center [&_.admin-logo]:rounded-[11px] [&_.admin-logo]:bg-[linear-gradient(145deg,#17233d,#2c416f)] [&_.admin-logo]:text-lg [&_.admin-logo]:font-bold [&_.admin-logo]:text-[#ee9e1e]
  [&_.admin-workspace]:grid [&_.admin-workspace]:h-[calc(100vh-72px)] [&_.admin-workspace]:grid-cols-[260px_minmax(460px,1fr)_360px] max-[1180px]:[&_.admin-workspace]:grid-cols-[230px_minmax(420px,1fr)_320px] max-[960px]:[&_.admin-workspace]:h-auto max-[960px]:[&_.admin-workspace]:min-h-[calc(100vh-72px)] max-[960px]:[&_.admin-workspace]:grid-cols-[220px_1fr] max-[680px]:[&_.admin-workspace]:block
  [&_.admin-sidebar]:overflow-auto [&_.admin-sidebar]:border-r [&_.admin-sidebar]:border-[#dce2e8] [&_.admin-sidebar]:bg-white max-[680px]:[&_.admin-sidebar]:border-r-0
  [&_.admin-editor-panel]:overflow-auto [&_.admin-editor-panel]:border-l [&_.admin-editor-panel]:border-[#dce2e8] [&_.admin-editor-panel]:bg-white [&_.admin-editor-panel]:p-6 max-[1180px]:[&_.admin-editor-panel]:p-[18px] max-[960px]:[&_.admin-editor-panel]:col-span-full max-[960px]:[&_.admin-editor-panel]:min-h-[420px] max-[960px]:[&_.admin-editor-panel]:border-l-0 max-[960px]:[&_.admin-editor-panel]:border-t
  [&_.admin-panel-section]:border-b [&_.admin-panel-section]:border-[#dce2e8] [&_.admin-panel-section]:px-[18px] [&_.admin-panel-section]:py-[22px] [&_.admin-panel-section_label]:mb-[7px] [&_.admin-panel-section_label]:block [&_.admin-panel-section_label]:text-xs [&_.admin-panel-section_label]:font-semibold
  [&_.admin-panel-section_input]:h-[42px] [&_.admin-panel-section_input]:w-full [&_.admin-panel-section_input]:rounded-[9px] [&_.admin-panel-section_input]:border [&_.admin-panel-section_input]:border-[#cfd7df] [&_.admin-panel-section_input]:px-[11px] [&_.admin-panel-section_select]:h-[42px] [&_.admin-panel-section_select]:w-full [&_.admin-panel-section_select]:rounded-[9px] [&_.admin-panel-section_select]:border [&_.admin-panel-section_select]:border-[#cfd7df] [&_.admin-panel-section_select]:px-[11px]
  [&_.admin-panel-section_input:focus]:border-[#ee9e1e] [&_.admin-panel-section_input:focus]:shadow-[0_0_0_3px_rgba(238,158,30,.14)] [&_.admin-panel-section_select:focus]:border-[#ee9e1e] [&_.admin-panel-section_select:focus]:shadow-[0_0_0_3px_rgba(238,158,30,.14)]
  [&_.admin-preview-panel]:flex [&_.admin-preview-panel]:min-w-0 [&_.admin-preview-panel]:flex-col [&_.admin-preview-panel]:bg-[#e8ecf1] [&_.admin-preview-panel]:p-[14px] max-[960px]:[&_.admin-preview-panel]:h-[680px] max-[680px]:[&_.admin-preview-panel]:h-[600px] max-[680px]:[&_.admin-preview-panel]:p-[10px]
  [&_.admin-preview-bar]:flex [&_.admin-preview-bar]:h-9 [&_.admin-preview-bar]:items-start [&_.admin-preview-bar]:justify-between [&_.admin-preview-bar]:text-xs [&_.admin-preview-bar]:text-[#526071] [&_.admin-preview-bar_a]:font-semibold [&_.admin-preview-bar_a]:text-[#8b5704]
  [&_.admin-preview-panel_iframe]:min-h-[520px] [&_.admin-preview-panel_iframe]:w-full [&_.admin-preview-panel_iframe]:flex-1 [&_.admin-preview-panel_iframe]:rounded-xl [&_.admin-preview-panel_iframe]:border [&_.admin-preview-panel_iframe]:border-[#cfd6de] [&_.admin-preview-panel_iframe]:bg-white [&_.admin-preview-panel_iframe]:shadow-[0_9px_30px_rgba(20,35,55,.12)]
  [&_.admin-section-title]:flex [&_.admin-section-title]:items-center [&_.admin-section-title]:justify-between [&_.admin-section-title_span]:rounded-full [&_.admin-section-title_span]:bg-[#fff3dc] [&_.admin-section-title_span]:px-2 [&_.admin-section-title_span]:py-0.5 [&_.admin-section-title_span]:text-xs [&_.admin-section-title_span]:font-bold [&_.admin-section-title_span]:text-[#975b00]
  [&_.admin-saved-row]:flex [&_.admin-saved-row]:items-center [&_.admin-saved-row]:gap-[7px] [&_.admin-saved-row]:border-t [&_.admin-saved-row]:border-[#eef1f4] [&_.admin-saved-row]:py-[9px] [&_.admin-saved-row_span]:flex-1 [&_.admin-saved-row_span]:truncate [&_.admin-saved-row_span]:text-xs [&_.admin-saved-row_span]:text-[#475467] [&_.admin-saved-row_button]:border-0 [&_.admin-saved-row_button]:bg-transparent [&_.admin-saved-row_button]:text-[11px] [&_.admin-saved-row_button]:font-bold [&_.admin-saved-row_button]:text-[#a86600]
  [&_.admin-editor-heading]:flex [&_.admin-editor-heading]:items-start [&_.admin-editor-heading]:justify-between [&_.admin-editor-heading]:gap-3 [&_.admin-editor-heading]:border-b [&_.admin-editor-heading]:border-[#dce2e8] [&_.admin-editor-heading]:pb-[18px] [&_.admin-editor-heading_h2]:m-0 [&_.admin-editor-heading_h2]:text-lg [&_.admin-editor-heading_h2]:text-[#17233d]
  [&_.admin-field]:mt-[19px] [&_.admin-field_label]:mb-[7px] [&_.admin-field_label]:block [&_.admin-field_label]:text-xs [&_.admin-field_label]:font-semibold [&_.admin-field_input]:h-[42px] [&_.admin-field_input]:px-[11px] [&_.admin-field_textarea]:min-h-[120px] [&_.admin-field_textarea]:resize-y [&_.admin-field_textarea]:leading-[1.55] [&_.admin-field_small]:mt-1.5 [&_.admin-field_small]:block [&_.admin-field_small]:text-[11px] [&_.admin-field_small]:text-[#687386]
  [&_.admin-actions]:sticky [&_.admin-actions]:bottom-[-24px] [&_.admin-actions]:z-[5] [&_.admin-actions]:mx-[-24px] [&_.admin-actions]:mt-6 [&_.admin-actions]:border-t [&_.admin-actions]:border-[#dce2e8] [&_.admin-actions]:bg-white/95 [&_.admin-actions]:px-6 [&_.admin-actions]:pb-5 [&_.admin-actions]:pt-4 [&_.admin-actions]:shadow-[0_-8px_22px_rgba(23,35,61,.08)]
  [&_.admin-secondary-button]:min-h-10 [&_.admin-secondary-button]:rounded-[9px] [&_.admin-secondary-button]:border [&_.admin-secondary-button]:border-[#cbd3dc] [&_.admin-secondary-button]:bg-white [&_.admin-secondary-button]:px-4 [&_.admin-secondary-button]:text-xs [&_.admin-secondary-button]:font-semibold [&_.admin-text-button]:min-h-10 [&_.admin-text-button]:rounded-[9px] [&_.admin-text-button]:px-4 [&_.admin-text-button]:text-xs [&_.admin-text-button]:font-semibold [&_.admin-danger-button]:min-h-10 [&_.admin-danger-button]:rounded-[9px] [&_.admin-danger-button]:bg-[#b42318] [&_.admin-danger-button]:px-4 [&_.admin-danger-button]:text-xs [&_.admin-danger-button]:font-semibold [&_.admin-danger-button]:text-white
  [&_.admin-blog-manager]:mx-auto [&_.admin-blog-manager]:max-w-[1800px] [&_.admin-blog-manager]:p-6 max-[900px]:[&_.admin-blog-manager]:p-[14px] max-[560px]:[&_.admin-blog-manager]:p-2
  [&_.admin-blog-toolbar]:sticky [&_.admin-blog-toolbar]:top-0 [&_.admin-blog-toolbar]:z-30 [&_.admin-blog-toolbar]:mb-5 [&_.admin-blog-toolbar]:flex [&_.admin-blog-toolbar]:items-center [&_.admin-blog-toolbar]:justify-between [&_.admin-blog-toolbar]:rounded-2xl [&_.admin-blog-toolbar]:border [&_.admin-blog-toolbar]:border-[#e1e6eb] [&_.admin-blog-toolbar]:bg-[linear-gradient(135deg,#fff_0%,#f8fafb_100%)] [&_.admin-blog-toolbar]:px-6 [&_.admin-blog-toolbar]:py-[22px] [&_.admin-blog-toolbar]:shadow-[0_10px_30px_rgba(23,35,61,.06)]
  [&_.admin-blog-toolbar_h2]:mt-[3px] [&_.admin-blog-toolbar_h2]:text-xl [&_.admin-blog-layout]:overflow-hidden [&_.admin-blog-layout]:rounded-2xl [&_.admin-blog-layout]:border [&_.admin-blog-layout]:border-[#e1e6eb] [&_.admin-blog-layout]:bg-[#f5f7f9] [&_.admin-blog-layout]:shadow-[0_16px_44px_rgba(23,35,61,.07)] [&_.admin-blog-layout.is-editing]:overflow-visible [&_.admin-blog-layout.is-editing]:border-0 [&_.admin-blog-layout.is-editing]:bg-transparent [&_.admin-blog-layout.is-editing]:shadow-none
  [&_.admin-blog-list]:min-h-[620px] [&_.admin-blog-list]:p-5 [&_.admin-blog-list-heading]:mb-[18px] [&_.admin-blog-list-heading]:flex [&_.admin-blog-list-heading]:items-center [&_.admin-blog-list-heading]:justify-between [&_.admin-blog-list-heading]:text-[#232555] [&_.admin-blog-list-scroll>button]:mb-2 [&_.admin-blog-list-scroll>button]:w-full [&_.admin-blog-list-scroll>button]:rounded-[10px] [&_.admin-blog-list-scroll>button]:border [&_.admin-blog-list-scroll>button]:border-[#e8ecf0] [&_.admin-blog-list-scroll>button]:bg-white [&_.admin-blog-list-scroll>button]:p-[13px] [&_.admin-blog-list-scroll>button]:text-left
  [&_.admin-blog-form-grid]:block [&_.admin-form-section]:mb-5 [&_.admin-form-section]:rounded-2xl [&_.admin-form-section]:p-6 [&_.admin-form-section]:shadow-[0_8px_26px_rgba(23,35,61,.05)] max-[560px]:[&_.admin-form-section]:p-[15px]
  [&_.admin-form-section-heading]:mb-[19px] [&_.admin-form-section-heading]:flex [&_.admin-form-section-heading]:items-start [&_.admin-form-section-heading]:gap-3 [&_.admin-form-section-heading]:border-b [&_.admin-form-section-heading]:border-[#edf0f2] [&_.admin-form-section-heading]:pb-4 [&_.admin-form-section-heading>span]:grid [&_.admin-form-section-heading>span]:h-[34px] [&_.admin-form-section-heading>span]:w-[34px] [&_.admin-form-section-heading>span]:place-items-center [&_.admin-form-section-heading>span]:rounded-[9px] [&_.admin-form-section-heading>span]:bg-[#eaf6f4] [&_.admin-form-section-heading>span]:font-extrabold [&_.admin-form-section-heading>span]:text-[#087b71]
  [&_.admin-form-fields]:grid [&_.admin-form-fields]:grid-cols-2 [&_.admin-form-fields]:gap-x-[18px] max-[900px]:[&_.admin-form-fields]:grid-cols-1 [&_.admin-field-wide]:col-span-full
  [&_.admin-block-builder]:grid [&_.admin-block-builder]:grid-cols-[220px_minmax(0,1fr)_320px] [&_.admin-block-builder]:grid-areas-[\"palette_canvas_preview\"] [&_.admin-block-builder]:gap-[14px] max-[1200px]:[&_.admin-block-builder]:grid-cols-[210px_minmax(0,1fr)] max-[1200px]:[&_.admin-block-builder]:grid-areas-[\"palette_preview\"_\"canvas_canvas\"] max-[680px]:[&_.admin-block-builder]:flex max-[680px]:[&_.admin-block-builder]:flex-col
  [&_.admin-block-palette]:[grid-area:palette] [&_.admin-block-palette]:sticky [&_.admin-block-palette]:top-[10px] [&_.admin-block-palette]:self-start [&_.admin-block-palette]:rounded-xl [&_.admin-block-palette]:border [&_.admin-block-palette]:border-[#dfe5ea] [&_.admin-block-palette]:bg-white [&_.admin-block-palette]:p-[14px]
  [&_.admin-block-canvas]:[grid-area:canvas] [&_.admin-block-canvas]:min-w-0 [&_.admin-block-canvas]:rounded-xl [&_.admin-block-canvas]:border [&_.admin-block-canvas]:border-[#dfe5ea] [&_.admin-block-canvas]:bg-[#f8fafb] [&_.admin-block-canvas]:p-[14px]
  [&_.admin-block-live-preview]:[grid-area:preview] [&_.admin-block-live-preview]:sticky [&_.admin-block-live-preview]:top-[10px] [&_.admin-block-live-preview]:max-h-[calc(100vh-120px)] [&_.admin-block-live-preview]:overflow-auto [&_.admin-block-live-preview]:rounded-xl [&_.admin-block-live-preview]:border [&_.admin-block-live-preview]:border-[#dfe5ea] [&_.admin-block-live-preview]:bg-[#e9edf2] [&_.admin-block-live-preview]:p-3
  [&_.admin-content-block]:mb-3 [&_.admin-content-block]:rounded-xl [&_.admin-content-block]:border [&_.admin-content-block]:border-[#dce3e9] [&_.admin-content-block]:bg-white [&_.admin-content-block]:p-[14px] [&_.admin-content-block]:shadow-[0_4px_14px_rgba(23,35,61,.045)]
  [&_.admin-preview-page]:min-h-[330px] [&_.admin-preview-page]:overflow-hidden [&_.admin-preview-page]:rounded-lg [&_.admin-preview-page]:bg-white [&_.admin-preview-page]:px-[15px] [&_.admin-preview-page]:py-[18px] [&_.admin-preview-page]:text-[#334155] [&_.admin-preview-page]:shadow-[0_5px_16px_rgba(23,35,61,.10)]
  [&_.admin-image-manager]:mt-[19px] [&_.admin-image-manager]:rounded-xl [&_.admin-image-manager]:border [&_.admin-image-manager]:border-[#dce2e8] [&_.admin-image-manager]:bg-[#fbfcfd] [&_.admin-image-manager]:p-[14px] [&_.admin-image-dropzone]:relative [&_.admin-image-dropzone]:flex [&_.admin-image-dropzone]:flex-col [&_.admin-image-dropzone]:items-center [&_.admin-image-dropzone]:rounded-[10px] [&_.admin-image-dropzone]:border [&_.admin-image-dropzone]:border-dashed [&_.admin-image-dropzone]:border-[#b9c4cf] [&_.admin-image-dropzone]:bg-white [&_.admin-image-dropzone]:px-3 [&_.admin-image-dropzone]:py-[18px] [&_.admin-image-dropzone]:text-center
  [&_.admin-blog-actions]:sticky [&_.admin-blog-actions]:bottom-0 [&_.admin-blog-actions]:z-40 [&_.admin-blog-actions]:mt-5 [&_.admin-blog-actions]:flex [&_.admin-blog-actions]:w-full [&_.admin-blog-actions]:flex-wrap [&_.admin-blog-actions]:items-center [&_.admin-blog-actions]:justify-between [&_.admin-blog-actions]:gap-3 [&_.admin-blog-actions]:rounded-[14px] [&_.admin-blog-actions]:border [&_.admin-blog-actions]:border-[#d5dde4] [&_.admin-blog-actions]:bg-white/95 [&_.admin-blog-actions]:px-[18px] [&_.admin-blog-actions]:py-4 [&_.admin-blog-actions]:shadow-[0_12px_35px_rgba(23,35,61,.18)] [&_.admin-blog-actions]:backdrop-blur-xl [&_.admin-blog-action-buttons]:flex [&_.admin-blog-action-buttons]:min-w-0 [&_.admin-blog-action-buttons]:flex-1 [&_.admin-blog-action-buttons]:flex-wrap [&_.admin-blog-action-buttons]:items-center [&_.admin-blog-action-buttons]:justify-end [&_.admin-blog-action-buttons]:gap-2 [&_.admin-blog-action-buttons>button]:whitespace-nowrap [&_.admin-blog-action-buttons>button]:shrink-0
  [&_.admin-blog-save-state]:flex [&_.admin-blog-save-state]:min-w-[190px] [&_.admin-blog-save-state]:items-center [&_.admin-blog-save-state]:gap-[10px] [&_.admin-blog-save-state>span]:h-[10px] [&_.admin-blog-save-state>span]:w-[10px] [&_.admin-blog-save-state>span]:rounded-full [&_.admin-blog-save-state>span]:bg-[#98a2b3] [&_.admin-blog-save-state>span.published]:bg-[#17a673]
  [&_.admin-rich-editor]:min-h-[120px] [&_.admin-rich-editor]:w-full [&_.admin-rich-editor]:whitespace-pre-wrap [&_.admin-rich-editor]:rounded-[9px] [&_.admin-rich-editor]:border [&_.admin-rich-editor]:border-[#cfd7df] [&_.admin-rich-editor]:bg-white [&_.admin-rich-editor]:p-[11px] [&_.admin-rich-editor]:text-sm [&_.admin-rich-editor]:leading-[1.55] [&_.admin-rich-editor:focus]:border-[#ee9e1e] [&_.admin-rich-editor:focus]:shadow-[0_0_0_3px_rgba(238,158,30,.14)]`;

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return <div className={`admin-root ${adminTailwind}`}>{children}</div>;
}
