"use client";
import { useEffect, useMemo, useState } from "react";
import type { KnowledgeEntry } from "@/app/types/chatbot";
const blank = (): KnowledgeEntry => ({ id: "", title: "", category: "faq", content: "", keywords: [], priority: 5, enabled: true });
export default function KnowledgeManager() {
  const [entries, setEntries] = useState<KnowledgeEntry[]>([]); const [editing, setEditing] = useState<KnowledgeEntry>(blank()); const [filter, setFilter] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [analytics, setAnalytics] = useState<Record<string, number>>({});
  const load = async () => { const response = await fetch("/api/admin/chatbot", { cache: "no-store" }); const data = await response.json(); if (response.ok) { setEntries(data.entries); setAnalytics(data.analytics); } };
  // Loading remote admin data is the synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => entries.filter((item) => `${item.title} ${item.category} ${item.keywords.join(" ")}`.toLowerCase().includes(filter.toLowerCase())), [entries, filter]);
  async function save() { setBusy(true); setNotice(""); try { const response = await fetch("/api/admin/chatbot", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setEditing(blank()); setNotice("Knowledge entry saved."); await load(); } catch (error) { setNotice((error as Error).message || "Save failed."); } finally { setBusy(false); } }
  async function remove(entry: KnowledgeEntry) { if (!confirm(`Delete “${entry.title}”?`)) return; setBusy(true); const response = await fetch("/api/admin/chatbot", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: entry.id, category: entry.category }) }); setNotice(response.ok ? "Entry deleted." : "Delete failed."); if (response.ok) { setEditing(blank()); await load(); } setBusy(false); }
  return <main className="kb-admin"><header><div><a href="/admin">← Admin</a><h1>Chatbot Knowledge Base</h1><p>Manage verified information supplied to the Trijotech AI assistant.</p></div><button type="button" onClick={() => setEditing(blank())}>New entry</button></header><section className="kb-stats">{Object.entries(analytics).map(([name, value]) => <div key={name}><strong>{value}</strong><span>{name}</span></div>)}</section>{notice && <p className="kb-notice" role="status">{notice}</p>}<div className="kb-layout"><aside><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Search knowledge…" aria-label="Search knowledge" />{shown.map((entry) => <button type="button" key={entry.id} onClick={() => setEditing({ ...entry, keywords: [...entry.keywords] })}><strong>{entry.title}</strong><span>{entry.category} · priority {entry.priority}</span></button>)}</aside><section className="kb-form"><h2>{editing.id ? "Edit entry" : "Add entry"}</h2><label>Title<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} /></label><div className="kb-row"><label>Category<input value={editing.category} onChange={(event) => setEditing({ ...editing, category: event.target.value })} /></label><label>Priority<input type="number" min="0" max="10" value={editing.priority} onChange={(event) => setEditing({ ...editing, priority: Number(event.target.value) })} /></label></div><label>Keywords<input value={editing.keywords.join(", ")} onChange={(event) => setEditing({ ...editing, keywords: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /><small>Comma-separated search terms.</small></label><label>Related website path<input value={editing.url || ""} onChange={(event) => setEditing({ ...editing, url: event.target.value })} placeholder="/services" /></label><label>Chatbot-ready content<textarea rows={10} value={editing.content} onChange={(event) => setEditing({ ...editing, content: event.target.value })} /></label><label className="kb-check"><input type="checkbox" checked={editing.enabled} onChange={(event) => setEditing({ ...editing, enabled: event.target.checked })} /> Enabled</label><div className="kb-actions"><button type="button" onClick={save} disabled={busy}>{busy ? "Saving…" : "Save entry"}</button>{editing.id && <button type="button" className="danger" onClick={() => remove(editing)} disabled={busy}>Delete</button>}</div><div className="kb-preview"><strong>Chatbot preview</strong><h3>{editing.title || "Entry title"}</h3><p>{editing.content || "The normalized knowledge content will appear here."}</p></div></section></div></main>;
}
