"use client";
import { useEffect, useState } from "react";
import type { ChatbotSettings } from "@/app/types/chatbot";
export default function SettingsManager() {
  const [settings, setSettings] = useState<ChatbotSettings | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void fetch("/api/admin/chatbot/settings").then((response) => response.json()).then((data) => { if (active) setSettings(data); }); return () => { active = false; }; }, []);
  async function save() { if (!settings) return; setBusy(true); const response = await fetch("/api/admin/chatbot/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); setNotice(response.ok ? "Chatbot settings saved." : data.error || "Settings could not be saved."); if (response.ok) setSettings(data.settings); setBusy(false); }
  if (!settings) return <section className="kb-settings"><p>Loading chatbot settings…</p></section>;
  return <section className="kb-settings"><h2>Chatbot Settings</h2><p>Public presentation and safety limits. Secrets are never shown here.</p>{notice && <div className="kb-notice">{notice}</div>}<div className="kb-settings-grid"><label className="kb-check"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} /> Chatbot enabled</label><label className="kb-check"><input type="checkbox" checked={settings.contactButton} onChange={(event) => setSettings({ ...settings, contactButton: event.target.checked })} /> Show contact-team button</label><label>Assistant name<input value={settings.assistantName} onChange={(event) => setSettings({ ...settings, assistantName: event.target.value })} /></label><label>Maximum message length<input type="number" min="100" max="2000" value={settings.maximumMessageLength} onChange={(event) => setSettings({ ...settings, maximumMessageLength: Number(event.target.value) })} /></label><label className="wide">Welcome message<textarea rows={3} value={settings.welcomeMessage} onChange={(event) => setSettings({ ...settings, welcomeMessage: event.target.value })} /></label><label className="wide">Fallback message<textarea rows={3} value={settings.fallbackMessage} onChange={(event) => setSettings({ ...settings, fallbackMessage: event.target.value })} /></label><label className="wide">Suggested questions<input value={settings.suggestedQuestions.join(" | ")} onChange={(event) => setSettings({ ...settings, suggestedQuestions: event.target.value.split("|").map((item) => item.trim()).filter(Boolean) })} /><small>Separate questions with |</small></label></div><button type="button" onClick={save} disabled={busy}>{busy ? "Saving…" : "Save settings"}</button></section>;
}
