import type { Metadata } from "next";
import { ContactButton, OfferingGrid, ServiceHero } from "../../components/LegacyServiceDetail";
export const metadata: Metadata={title:"SAP Support & Application Management Services"};
const offerings=[
{title:"Functional & Technical SAP Support",description:"We deliver end-to-end support to strengthen financial accuracy and data-driven decision-making. We enable smarter planning, real-time insights, and greater transparency across your enterprise."},
{title:"Post-Go-Live Stabilization",description:"The real test begins after go-live. We help stabilize processes, resolve transition hiccups, and reinforce system adoption through structured support, ensuring a smooth shift to steady-state operations."},
{title:"Change, Upgrade & Release Management",description:"Managing SAP updates, enhancements, and version upgrades without disrupting business? That’s our strength. We apply robust governance and testing practices to ensure smooth transitions."},
{title:"System Performance Optimization",description:"Lagging reports or slow transactions? We proactively analyze and optimize system performance to enhance response times, process efficiency, and overall user experience."},
{title:"Security, Compliance & Role Management",description:"Protect your SAP environment with structured access controls, compliance audits, and user role reviews—ensuring data integrity and regulatory alignment."},
{title:"Flexible Engagement Models",description:"Whether you need dedicated support, shared resources, or hybrid models, we offer tailored SLAs, scalable teams, and ticket-based or outcome-driven support aligned to your operations."}];
const industries=["L0601.jpg","L0602.jpg","L0603.jpg","L0604.jpg","L0605.jpg","L0606.jpg"];
export default function Page(){return <main className="legacy-service-source-page"><ServiceHero title="SAP Support & Application Management Services" image="/assets/image/Blogs1.png"/><OfferingGrid heading={<>End-to-End SAP <em>Support</em></>} intro="At Trijotech, our commitment doesn’t end with implementation. We ensure your SAP systems remain resilient, responsive, and aligned with your business objectives—every day. Our SAP Support & AMS (Application Management Services) are built to deliver operational continuity, performance assurance, and ongoing value from your SAP investments." cards={offerings}/><section className="support-industries"><div className="container"><div className="section-heading"><h2>Industries <em>We Serve</em></h2><p>Every industry has its own challenges—and we understand that. Our AMS team brings industry-specific experience to ensure we deliver relevant, effective solutions for:</p></div><div className="support-industry-grid">{industries.map((image,index)=><div key={image}><img src={`/assets/image/${image}`} alt={`Industry ${index+1}`}/></div>)}</div><div className="support-growth"><h3>Support That Grows With You</h3><p>Your business isn’t static—and neither should your SAP support be. Whether you’re running a dynamic S/4HANA landscape or a cloud-integrated hybrid model, Trijotech ensures you’re always equipped for what’s next.</p></div></div></section><ContactButton/></main>}
